development:
  adapter: postgresql
  encoding: unicode
  database: htmlparser
  pool: 5
  username: postgres
  password: postgres
  key: <<key>>
test:
  adapter: postgresql
  encoding: unicode
  database: htmlparser_test
  pool: 5
  username: postgres
  password: postgres
